/** UUID v4, generated by the application layer via crypto.randomUUID(). */
export type Id = string;

/** ISO-8601 with milliseconds and timezone offset, e.g. "2026-09-22T19:04:11.482+02:00". */
export type IsoTimestamp = string;

/** Calendar date, "YYYY-MM-DD". */
export type IsoDate = string;

/** The only two parties the app knows about. */
export type TeamSide = 'us' | 'them';

export const TEAM_SIDES: readonly TeamSide[] = ['us', 'them'] as const;

/** Current schema of every persisted root document. */
export const SCHEMA_VERSION = 1 as const;
export type SchemaVersion = typeof SCHEMA_VERSION;

/** Score pair, always "our points first". */
export interface Score {
  readonly us: number;
  readonly them: number;
}

export const ZERO_SCORE: Score = { us: 0, them: 0 };

export function otherSide(side: TeamSide): TeamSide {
  return side === 'us' ? 'them' : 'us';
}

export function pointsOf(score: Score, side: TeamSide): number {
  return side === 'us' ? score.us : score.them;
}
