/**
 * Writes dist/sw.js with the exact asset list produced by the build.
 *
 * The app never calls the network at runtime, so the worker can serve everything from the
 * cache and only fall back to the network for things it has never seen. Source maps stay out
 * of the precache: they are several megabytes and are useless on a tablet.
 */
import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath, URL } from 'node:url';
import path from 'node:path';

const distDir = fileURLToPath(new URL('../dist', import.meta.url));

async function collect(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const absolute = path.join(dir, entry.name);
      if (entry.isDirectory()) return collect(absolute);
      return [absolute];
    }),
  );
  return files.flat();
}

const absolute = await collect(distDir);
const assets = absolute
  .map((file) => path.relative(distDir, file).split(path.sep).join('/'))
  .filter((file) => !file.endsWith('.map') && file !== 'sw.js')
  .sort();

if (!assets.includes('index.html')) {
  throw new Error('dist/index.html is missing: run the build first');
}

// The cache name has to change whenever any asset changes, or browsers keep serving the old app.
const fingerprint = createHash('sha256');
for (const asset of assets) {
  fingerprint.update(asset);
  fingerprint.update(await readFile(path.join(distDir, asset)));
}
const version = fingerprint.digest('hex').slice(0, 12);

const worker = `// Generated by scripts/buildServiceWorker.mjs. Do not edit by hand.
const CACHE = 'volley-scout-${version}';
const ASSETS = ${JSON.stringify(assets, null, 2)};

self.addEventListener('install', (event) => {
  // No skipWaiting: a new build must never swap assets under a match in progress.
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(ASSETS.map((asset) => new URL(asset, self.registration.scope).href))),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(names.filter((name) => name !== CACHE).map((name) => caches.delete(name)));
      await self.clients.claim();
    })(),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  if (new URL(request.url).origin !== self.location.origin) return;

  // Every route lives behind the hash, so any navigation resolves to the one shell document.
  if (request.mode === 'navigate') {
    event.respondWith(
      caches
        .match(new URL('index.html', self.registration.scope).href)
        .then((cached) => cached ?? fetch(request)),
    );
    return;
  }

  event.respondWith(caches.match(request).then((cached) => cached ?? fetch(request)));
});
`;

await writeFile(path.join(distDir, 'sw.js'), worker, 'utf8');
console.log(`sw.js written: ${String(assets.length)} assets, cache volley-scout-${version}`);
